title : Tomorrow
tagline: To Be Myself
author :
  name : xiaoming lui
  email : xiaominglui@gmail.com
  github : xiaominglui
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
